- hosts: awx
  become: yes
  user: vagrant
  gather_facts: no
  pre_tasks:
    - name: 'Update o Repo'
      raw: 'apt-get -y update'
    - name: 'Install o Python'
      raw: 'apt-get install -y python'
- hosts: awx
  become: yes
  user: vagrant
  roles:
  - { role: install-awx, tags: ["install_awx"]}